import { Country } from './types/interfaces/Country';

// Countries and states data with ISO codes for flag-icons
// Based on https://github.com/dr5hn/countries-states-cities-database

// Major countries with their states/provinces
export const COUNTRIES: Country[] = [
  {
    name: 'Australia',
    iso2: 'AU',
    states: [
      { name: 'Australian Capital Territory', state_code: 'ACT' },
      { name: 'New South Wales', state_code: 'NSW' },
      { name: 'Northern Territory', state_code: 'NT' },
      { name: 'Queensland', state_code: 'QLD' },
      { name: 'South Australia', state_code: 'SA' },
      { name: 'Tasmania', state_code: 'TAS' },
      { name: 'Victoria', state_code: 'VIC' },
      { name: 'Western Australia', state_code: 'WA' },
    ],
  },
  {
    name: 'Canada',
    iso2: 'CA',
    states: [
      { name: 'Alberta', state_code: 'AB' },
      { name: 'British Columbia', state_code: 'BC' },
      { name: 'Manitoba', state_code: 'MB' },
      { name: 'New Brunswick', state_code: 'NB' },
      { name: 'Newfoundland and Labrador', state_code: 'NL' },
      { name: 'Northwest Territories', state_code: 'NT' },
      { name: 'Nova Scotia', state_code: 'NS' },
      { name: 'Nunavut', state_code: 'NU' },
      { name: 'Ontario', state_code: 'ON' },
      { name: 'Prince Edward Island', state_code: 'PE' },
      { name: 'Quebec', state_code: 'QC' },
      { name: 'Saskatchewan', state_code: 'SK' },
      { name: 'Yukon', state_code: 'YT' },
    ],
  },
  {
    name: 'United States',
    iso2: 'US',
    states: [
      { name: 'Alabama', state_code: 'AL' },
      { name: 'Alaska', state_code: 'AK' },
      { name: 'Arizona', state_code: 'AZ' },
      { name: 'Arkansas', state_code: 'AR' },
      { name: 'California', state_code: 'CA' },
      { name: 'Colorado', state_code: 'CO' },
      { name: 'Connecticut', state_code: 'CT' },
      { name: 'Delaware', state_code: 'DE' },
      { name: 'Florida', state_code: 'FL' },
      { name: 'Georgia', state_code: 'GA' },
      { name: 'Hawaii', state_code: 'HI' },
      { name: 'Idaho', state_code: 'ID' },
      { name: 'Illinois', state_code: 'IL' },
      { name: 'Indiana', state_code: 'IN' },
      { name: 'Iowa', state_code: 'IA' },
      { name: 'Kansas', state_code: 'KS' },
      { name: 'Kentucky', state_code: 'KY' },
      { name: 'Louisiana', state_code: 'LA' },
      { name: 'Maine', state_code: 'ME' },
      { name: 'Maryland', state_code: 'MD' },
      { name: 'Massachusetts', state_code: 'MA' },
      { name: 'Michigan', state_code: 'MI' },
      { name: 'Minnesota', state_code: 'MN' },
      { name: 'Mississippi', state_code: 'MS' },
      { name: 'Missouri', state_code: 'MO' },
      { name: 'Montana', state_code: 'MT' },
      { name: 'Nebraska', state_code: 'NE' },
      { name: 'Nevada', state_code: 'NV' },
      { name: 'New Hampshire', state_code: 'NH' },
      { name: 'New Jersey', state_code: 'NJ' },
      { name: 'New Mexico', state_code: 'NM' },
      { name: 'New York', state_code: 'NY' },
      { name: 'North Carolina', state_code: 'NC' },
      { name: 'North Dakota', state_code: 'ND' },
      { name: 'Ohio', state_code: 'OH' },
      { name: 'Oklahoma', state_code: 'OK' },
      { name: 'Oregon', state_code: 'OR' },
      { name: 'Pennsylvania', state_code: 'PA' },
      { name: 'Rhode Island', state_code: 'RI' },
      { name: 'South Carolina', state_code: 'SC' },
      { name: 'South Dakota', state_code: 'SD' },
      { name: 'Tennessee', state_code: 'TN' },
      { name: 'Texas', state_code: 'TX' },
      { name: 'Utah', state_code: 'UT' },
      { name: 'Vermont', state_code: 'VT' },
      { name: 'Virginia', state_code: 'VA' },
      { name: 'Washington', state_code: 'WA' },
      { name: 'West Virginia', state_code: 'WV' },
      { name: 'Wisconsin', state_code: 'WI' },
      { name: 'Wyoming', state_code: 'WY' },
    ],
  },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    states: [
      { name: 'England', state_code: 'ENG' },
      { name: 'Northern Ireland', state_code: 'NIR' },
      { name: 'Scotland', state_code: 'SCT' },
      { name: 'Wales', state_code: 'WLS' },
    ],
  },
  {
    name: 'Germany',
    iso2: 'DE',
    states: [
      { name: 'Baden-Württemberg', state_code: 'BW' },
      { name: 'Bavaria', state_code: 'BY' },
      { name: 'Berlin', state_code: 'BE' },
      { name: 'Brandenburg', state_code: 'BB' },
      { name: 'Bremen', state_code: 'HB' },
      { name: 'Hamburg', state_code: 'HH' },
      { name: 'Hesse', state_code: 'HE' },
      { name: 'Lower Saxony', state_code: 'NI' },
      { name: 'Mecklenburg-Vorpommern', state_code: 'MV' },
      { name: 'North Rhine-Westphalia', state_code: 'NW' },
      { name: 'Rhineland-Palatinate', state_code: 'RP' },
      { name: 'Saarland', state_code: 'SL' },
      { name: 'Saxony', state_code: 'SN' },
      { name: 'Saxony-Anhalt', state_code: 'ST' },
      { name: 'Schleswig-Holstein', state_code: 'SH' },
      { name: 'Thuringia', state_code: 'TH' },
    ],
  },
  {
    name: 'France',
    iso2: 'FR',
    states: [
      { name: 'Auvergne-Rhône-Alpes', state_code: 'ARA' },
      { name: 'Bourgogne-Franche-Comté', state_code: 'BFC' },
      { name: 'Bretagne', state_code: 'BRE' },
      { name: 'Centre-Val de Loire', state_code: 'CVL' },
      { name: 'Corse', state_code: 'COR' },
      { name: 'Grand Est', state_code: 'GES' },
      { name: 'Hauts-de-France', state_code: 'HDF' },
      { name: 'Île-de-France', state_code: 'IDF' },
      { name: 'Normandie', state_code: 'NOR' },
      { name: 'Nouvelle-Aquitaine', state_code: 'NAQ' },
      { name: 'Occitanie', state_code: 'OCC' },
      { name: 'Pays de la Loire', state_code: 'PDL' },
      { name: "Provence-Alpes-Côte d'Azur", state_code: 'PAC' },
    ],
  },
  {
    name: 'Italy',
    iso2: 'IT',
    states: [
      { name: 'Abruzzo', state_code: '65' },
      { name: 'Basilicata', state_code: '77' },
      { name: 'Calabria', state_code: '78' },
      { name: 'Campania', state_code: '72' },
      { name: 'Emilia-Romagna', state_code: '45' },
      { name: 'Friuli Venezia Giulia', state_code: '36' },
      { name: 'Lazio', state_code: '62' },
      { name: 'Liguria', state_code: '42' },
      { name: 'Lombardia', state_code: '25' },
      { name: 'Marche', state_code: '57' },
      { name: 'Molise', state_code: '67' },
      { name: 'Piemonte', state_code: '21' },
      { name: 'Puglia', state_code: '75' },
      { name: 'Sardegna', state_code: '88' },
      { name: 'Sicilia', state_code: '82' },
      { name: 'Toscana', state_code: '52' },
      { name: 'Trentino-Alto Adige', state_code: '32' },
      { name: 'Umbria', state_code: '55' },
      { name: "Valle d'Aosta", state_code: '23' },
      { name: 'Veneto', state_code: '34' },
    ],
  },
  {
    name: 'Spain',
    iso2: 'ES',
    states: [
      { name: 'Andalucía', state_code: 'AN' },
      { name: 'Aragón', state_code: 'AR' },
      { name: 'Asturias', state_code: 'AS' },
      { name: 'Cantabria', state_code: 'CB' },
      { name: 'Castilla y León', state_code: 'CL' },
      { name: 'Castilla-La Mancha', state_code: 'CM' },
      { name: 'Cataluña', state_code: 'CT' },
      { name: 'Ceuta', state_code: 'CE' },
      { name: 'Comunidad de Madrid', state_code: 'MD' },
      { name: 'Comunidad Foral de Navarra', state_code: 'NC' },
      { name: 'Comunidad Valenciana', state_code: 'VC' },
      { name: 'Extremadura', state_code: 'EX' },
      { name: 'Galicia', state_code: 'GA' },
      { name: 'Islas Baleares', state_code: 'IB' },
      { name: 'Islas Canarias', state_code: 'CN' },
      { name: 'La Rioja', state_code: 'RI' },
      { name: 'Melilla', state_code: 'ML' },
      { name: 'País Vasco', state_code: 'PV' },
      { name: 'Principado de Asturias', state_code: 'O' },
      { name: 'Región de Murcia', state_code: 'MC' },
    ],
  },
  {
    name: 'Japan',
    iso2: 'JP',
    states: [
      { name: 'Aichi', state_code: '23' },
      { name: 'Akita', state_code: '05' },
      { name: 'Aomori', state_code: '02' },
      { name: 'Chiba', state_code: '12' },
      { name: 'Ehime', state_code: '38' },
      { name: 'Fukui', state_code: '18' },
      { name: 'Fukuoka', state_code: '40' },
      { name: 'Fukushima', state_code: '07' },
      { name: 'Gifu', state_code: '21' },
      { name: 'Gunma', state_code: '10' },
      { name: 'Hiroshima', state_code: '34' },
      { name: 'Hokkaido', state_code: '01' },
      { name: 'Hyogo', state_code: '28' },
      { name: 'Ibaraki', state_code: '08' },
      { name: 'Ishikawa', state_code: '17' },
      { name: 'Iwate', state_code: '03' },
      { name: 'Kagawa', state_code: '37' },
      { name: 'Kagoshima', state_code: '46' },
      { name: 'Kanagawa', state_code: '14' },
      { name: 'Kochi', state_code: '39' },
      { name: 'Kumamoto', state_code: '43' },
      { name: 'Kyoto', state_code: '26' },
      { name: 'Mie', state_code: '24' },
      { name: 'Miyagi', state_code: '04' },
      { name: 'Miyazaki', state_code: '45' },
      { name: 'Nagano', state_code: '20' },
      { name: 'Nagasaki', state_code: '42' },
      { name: 'Nara', state_code: '29' },
      { name: 'Niigata', state_code: '15' },
      { name: 'Oita', state_code: '44' },
      { name: 'Okayama', state_code: '33' },
      { name: 'Okinawa', state_code: '47' },
      { name: 'Osaka', state_code: '27' },
      { name: 'Saga', state_code: '41' },
      { name: 'Saitama', state_code: '11' },
      { name: 'Shiga', state_code: '25' },
      { name: 'Shimane', state_code: '32' },
      { name: 'Shizuoka', state_code: '22' },
      { name: 'Tochigi', state_code: '09' },
      { name: 'Tokushima', state_code: '36' },
      { name: 'Tokyo', state_code: '13' },
      { name: 'Tottori', state_code: '31' },
      { name: 'Toyama', state_code: '16' },
      { name: 'Wakayama', state_code: '30' },
      { name: 'Yamagata', state_code: '06' },
      { name: 'Yamaguchi', state_code: '35' },
      { name: 'Yamanashi', state_code: '19' },
    ],
  },
  {
    name: 'India',
    iso2: 'IN',
    states: [
      { name: 'Andhra Pradesh', state_code: 'AP' },
      { name: 'Arunachal Pradesh', state_code: 'AR' },
      { name: 'Assam', state_code: 'AS' },
      { name: 'Bihar', state_code: 'BR' },
      { name: 'Chhattisgarh', state_code: 'CT' },
      { name: 'Goa', state_code: 'GA' },
      { name: 'Gujarat', state_code: 'GJ' },
      { name: 'Haryana', state_code: 'HR' },
      { name: 'Himachal Pradesh', state_code: 'HP' },
      { name: 'Jharkhand', state_code: 'JH' },
      { name: 'Karnataka', state_code: 'KA' },
      { name: 'Kerala', state_code: 'KL' },
      { name: 'Madhya Pradesh', state_code: 'MP' },
      { name: 'Maharashtra', state_code: 'MH' },
      { name: 'Manipur', state_code: 'MN' },
      { name: 'Meghalaya', state_code: 'ML' },
      { name: 'Mizoram', state_code: 'MZ' },
      { name: 'Nagaland', state_code: 'NL' },
      { name: 'Odisha', state_code: 'OR' },
      { name: 'Punjab', state_code: 'PB' },
      { name: 'Rajasthan', state_code: 'RJ' },
      { name: 'Sikkim', state_code: 'SK' },
      { name: 'Tamil Nadu', state_code: 'TN' },
      { name: 'Telangana', state_code: 'TS' },
      { name: 'Tripura', state_code: 'TR' },
      { name: 'Uttar Pradesh', state_code: 'UP' },
      { name: 'Uttarakhand', state_code: 'UT' },
      { name: 'West Bengal', state_code: 'WB' },
    ],
  },
  {
    name: 'Brazil',
    iso2: 'BR',
    states: [
      { name: 'Acre', state_code: 'AC' },
      { name: 'Alagoas', state_code: 'AL' },
      { name: 'Amapá', state_code: 'AP' },
      { name: 'Amazonas', state_code: 'AM' },
      { name: 'Bahia', state_code: 'BA' },
      { name: 'Ceará', state_code: 'CE' },
      { name: 'Distrito Federal', state_code: 'DF' },
      { name: 'Espírito Santo', state_code: 'ES' },
      { name: 'Goiás', state_code: 'GO' },
      { name: 'Maranhão', state_code: 'MA' },
      { name: 'Mato Grosso', state_code: 'MT' },
      { name: 'Mato Grosso do Sul', state_code: 'MS' },
      { name: 'Minas Gerais', state_code: 'MG' },
      { name: 'Pará', state_code: 'PA' },
      { name: 'Paraíba', state_code: 'PB' },
      { name: 'Paraná', state_code: 'PR' },
      { name: 'Pernambuco', state_code: 'PE' },
      { name: 'Piauí', state_code: 'PI' },
      { name: 'Rio de Janeiro', state_code: 'RJ' },
      { name: 'Rio Grande do Norte', state_code: 'RN' },
      { name: 'Rio Grande do Sul', state_code: 'RS' },
      { name: 'Rondônia', state_code: 'RO' },
      { name: 'Roraima', state_code: 'RR' },
      { name: 'Santa Catarina', state_code: 'SC' },
      { name: 'São Paulo', state_code: 'SP' },
      { name: 'Sergipe', state_code: 'SE' },
      { name: 'Tocantins', state_code: 'TO' },
    ],
  },
];

// All countries (simplified list for countries without states)
export const ALL_COUNTRIES = [
  { name: 'Afghanistan', iso2: 'AF' },
  { name: 'Albania', iso2: 'AL' },
  { name: 'Algeria', iso2: 'DZ' },
  { name: 'Andorra', iso2: 'AD' },
  { name: 'Angola', iso2: 'AO' },
  { name: 'Antigua and Barbuda', iso2: 'AG' },
  { name: 'Argentina', iso2: 'AR' },
  { name: 'Armenia', iso2: 'AM' },
  { name: 'Austria', iso2: 'AT' },
  { name: 'Azerbaijan', iso2: 'AZ' },
  { name: 'Bahamas', iso2: 'BS' },
  { name: 'Bahrain', iso2: 'BH' },
  { name: 'Bangladesh', iso2: 'BD' },
  { name: 'Barbados', iso2: 'BB' },
  { name: 'Belarus', iso2: 'BY' },
  { name: 'Belgium', iso2: 'BE' },
  { name: 'Belize', iso2: 'BZ' },
  { name: 'Benin', iso2: 'BJ' },
  { name: 'Bhutan', iso2: 'BT' },
  { name: 'Bolivia', iso2: 'BO' },
  { name: 'Bosnia and Herzegovina', iso2: 'BA' },
  { name: 'Botswana', iso2: 'BW' },
  { name: 'Brunei', iso2: 'BN' },
  { name: 'Bulgaria', iso2: 'BG' },
  { name: 'Burkina Faso', iso2: 'BF' },
  { name: 'Burundi', iso2: 'BI' },
  { name: 'Cabo Verde', iso2: 'CV' },
  { name: 'Cambodia', iso2: 'KH' },
  { name: 'Cameroon', iso2: 'CM' },
  { name: 'Central African Republic', iso2: 'CF' },
  { name: 'Chad', iso2: 'TD' },
  { name: 'Chile', iso2: 'CL' },
  { name: 'China', iso2: 'CN' },
  { name: 'Colombia', iso2: 'CO' },
  { name: 'Comoros', iso2: 'KM' },
  { name: 'Congo', iso2: 'CG' },
  { name: 'Costa Rica', iso2: 'CR' },
  { name: 'Croatia', iso2: 'HR' },
  { name: 'Cuba', iso2: 'CU' },
  { name: 'Cyprus', iso2: 'CY' },
  { name: 'Czech Republic', iso2: 'CZ' },
  { name: 'Democratic Republic of the Congo', iso2: 'CD' },
  { name: 'Denmark', iso2: 'DK' },
  { name: 'Djibouti', iso2: 'DJ' },
  { name: 'Dominica', iso2: 'DM' },
  { name: 'Dominican Republic', iso2: 'DO' },
  { name: 'Ecuador', iso2: 'EC' },
  { name: 'Egypt', iso2: 'EG' },
  { name: 'El Salvador', iso2: 'SV' },
  { name: 'Equatorial Guinea', iso2: 'GQ' },
  { name: 'Eritrea', iso2: 'ER' },
  { name: 'Estonia', iso2: 'EE' },
  { name: 'Eswatini', iso2: 'SZ' },
  { name: 'Ethiopia', iso2: 'ET' },
  { name: 'Fiji', iso2: 'FJ' },
  { name: 'Finland', iso2: 'FI' },
  { name: 'Gabon', iso2: 'GA' },
  { name: 'Gambia', iso2: 'GM' },
  { name: 'Georgia', iso2: 'GE' },
  { name: 'Ghana', iso2: 'GH' },
  { name: 'Greece', iso2: 'GR' },
  { name: 'Grenada', iso2: 'GD' },
  { name: 'Guatemala', iso2: 'GT' },
  { name: 'Guinea', iso2: 'GN' },
  { name: 'Guinea-Bissau', iso2: 'GW' },
  { name: 'Guyana', iso2: 'GY' },
  { name: 'Haiti', iso2: 'HT' },
  { name: 'Honduras', iso2: 'HN' },
  { name: 'Hungary', iso2: 'HU' },
  { name: 'Iceland', iso2: 'IS' },
  { name: 'Indonesia', iso2: 'ID' },
  { name: 'Iran', iso2: 'IR' },
  { name: 'Iraq', iso2: 'IQ' },
  { name: 'Ireland', iso2: 'IE' },
  { name: 'Israel', iso2: 'IL' },
  { name: 'Ivory Coast', iso2: 'CI' },
  { name: 'Jamaica', iso2: 'JM' },
  { name: 'Jordan', iso2: 'JO' },
  { name: 'Kazakhstan', iso2: 'KZ' },
  { name: 'Kenya', iso2: 'KE' },
  { name: 'Kiribati', iso2: 'KI' },
  { name: 'Kuwait', iso2: 'KW' },
  { name: 'Kyrgyzstan', iso2: 'KG' },
  { name: 'Laos', iso2: 'LA' },
  { name: 'Latvia', iso2: 'LV' },
  { name: 'Lebanon', iso2: 'LB' },
  { name: 'Lesotho', iso2: 'LS' },
  { name: 'Liberia', iso2: 'LR' },
  { name: 'Libya', iso2: 'LY' },
  { name: 'Liechtenstein', iso2: 'LI' },
  { name: 'Lithuania', iso2: 'LT' },
  { name: 'Luxembourg', iso2: 'LU' },
  { name: 'Madagascar', iso2: 'MG' },
  { name: 'Malawi', iso2: 'MW' },
  { name: 'Malaysia', iso2: 'MY' },
  { name: 'Maldives', iso2: 'MV' },
  { name: 'Mali', iso2: 'ML' },
  { name: 'Malta', iso2: 'MT' },
  { name: 'Marshall Islands', iso2: 'MH' },
  { name: 'Mauritania', iso2: 'MR' },
  { name: 'Mauritius', iso2: 'MU' },
  { name: 'Mexico', iso2: 'MX' },
  { name: 'Micronesia', iso2: 'FM' },
  { name: 'Moldova', iso2: 'MD' },
  { name: 'Monaco', iso2: 'MC' },
  { name: 'Mongolia', iso2: 'MN' },
  { name: 'Montenegro', iso2: 'ME' },
  { name: 'Morocco', iso2: 'MA' },
  { name: 'Mozambique', iso2: 'MZ' },
  { name: 'Myanmar', iso2: 'MM' },
  { name: 'Namibia', iso2: 'NA' },
  { name: 'Nauru', iso2: 'NR' },
  { name: 'Nepal', iso2: 'NP' },
  { name: 'Netherlands', iso2: 'NL' },
  { name: 'New Zealand', iso2: 'NZ' },
  { name: 'Nicaragua', iso2: 'NI' },
  { name: 'Niger', iso2: 'NE' },
  { name: 'Nigeria', iso2: 'NG' },
  { name: 'North Korea', iso2: 'KP' },
  { name: 'North Macedonia', iso2: 'MK' },
  { name: 'Norway', iso2: 'NO' },
  { name: 'Oman', iso2: 'OM' },
  { name: 'Pakistan', iso2: 'PK' },
  { name: 'Palau', iso2: 'PW' },
  { name: 'Palestine', iso2: 'PS' },
  { name: 'Panama', iso2: 'PA' },
  { name: 'Papua New Guinea', iso2: 'PG' },
  { name: 'Paraguay', iso2: 'PY' },
  { name: 'Peru', iso2: 'PE' },
  { name: 'Philippines', iso2: 'PH' },
  { name: 'Poland', iso2: 'PL' },
  { name: 'Portugal', iso2: 'PT' },
  { name: 'Qatar', iso2: 'QA' },
  { name: 'Romania', iso2: 'RO' },
  { name: 'Russia', iso2: 'RU' },
  { name: 'Rwanda', iso2: 'RW' },
  { name: 'Saint Kitts and Nevis', iso2: 'KN' },
  { name: 'Saint Lucia', iso2: 'LC' },
  { name: 'Saint Vincent and the Grenadines', iso2: 'VC' },
  { name: 'Samoa', iso2: 'WS' },
  { name: 'San Marino', iso2: 'SM' },
  { name: 'Sao Tome and Principe', iso2: 'ST' },
  { name: 'Saudi Arabia', iso2: 'SA' },
  { name: 'Senegal', iso2: 'SN' },
  { name: 'Serbia', iso2: 'RS' },
  { name: 'Seychelles', iso2: 'SC' },
  { name: 'Sierra Leone', iso2: 'SL' },
  { name: 'Singapore', iso2: 'SG' },
  { name: 'Slovakia', iso2: 'SK' },
  { name: 'Slovenia', iso2: 'SI' },
  { name: 'Solomon Islands', iso2: 'SB' },
  { name: 'Somalia', iso2: 'SO' },
  { name: 'South Africa', iso2: 'ZA' },
  { name: 'South Korea', iso2: 'KR' },
  { name: 'South Sudan', iso2: 'SS' },
  { name: 'Sri Lanka', iso2: 'LK' },
  { name: 'Sudan', iso2: 'SD' },
  { name: 'Suriname', iso2: 'SR' },
  { name: 'Sweden', iso2: 'SE' },
  { name: 'Switzerland', iso2: 'CH' },
  { name: 'Syria', iso2: 'SY' },
  { name: 'Taiwan', iso2: 'TW' },
  { name: 'Tajikistan', iso2: 'TJ' },
  { name: 'Tanzania', iso2: 'TZ' },
  { name: 'Thailand', iso2: 'TH' },
  { name: 'Timor-Leste', iso2: 'TL' },
  { name: 'Togo', iso2: 'TG' },
  { name: 'Tonga', iso2: 'TO' },
  { name: 'Trinidad and Tobago', iso2: 'TT' },
  { name: 'Tunisia', iso2: 'TN' },
  { name: 'Turkey', iso2: 'TR' },
  { name: 'Turkmenistan', iso2: 'TM' },
  { name: 'Tuvalu', iso2: 'TV' },
  { name: 'Uganda', iso2: 'UG' },
  { name: 'Ukraine', iso2: 'UA' },
  { name: 'United Arab Emirates', iso2: 'AE' },
  { name: 'Uruguay', iso2: 'UY' },
  { name: 'Uzbekistan', iso2: 'UZ' },
  { name: 'Vanuatu', iso2: 'VU' },
  { name: 'Vatican City', iso2: 'VA' },
  { name: 'Venezuela', iso2: 'VE' },
  { name: 'Vietnam', iso2: 'VN' },
  { name: 'Yemen', iso2: 'YE' },
  { name: 'Zambia', iso2: 'ZM' },
  { name: 'Zimbabwe', iso2: 'ZW' },
];

// Helper function to get country by name
export function getCountryByName(name: string) {
  const countryWithStates = COUNTRIES.find((country) => country.name === name);
  if (countryWithStates) return countryWithStates;

  const simpleCountry = ALL_COUNTRIES.find((country) => country.name === name);
  if (simpleCountry) {
    return { ...simpleCountry, states: [] };
  }

  return null;
}

// Helper function to get all countries (for backward compatibility)
export function getAllCountries() {
  return [
    ...COUNTRIES,
    ...ALL_COUNTRIES.filter(
      (country) => !COUNTRIES.some((cws) => cws.name === country.name)
    ),
  ];
}

// Helper function to get states for a country
export function getStatesForCountry(countryName: string) {
  const country = COUNTRIES.find((country) => country.name === countryName);
  return country ? country.states : [];
}
