import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  mainSidebar: [{ type: 'autogenerated', dirName: '.' }],

  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Certificate System',
      items: [
        'certificate-system/overview',
        'certificate-system/templates',
        'certificate-system/generation',
        'certificate-system/variables',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/setup',
        'development/api',
        'development/testing',
      ],
    },
  ],
   */
};

export default sidebars;
