name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**

defaults:
  run:
    shell: bash
    working-directory: ./docs

jobs:
  build:
    name: Build Docusaurus site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Yarn Berry
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build website
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  deploy:
    name: Deploy docs to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
